name: Daily Commit

on:
  schedule:
    - cron: '30 0 * * *'  # Runs daily at 00:30 UTC
  workflow_dispatch:  # Allows manual trigger for testing

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions@github.com"

      - name: Create a Dummy Commit
        run: |
          echo "Last run: $(date)" > last-run.txt
          git add last-run.txt
          git commit -m "Automated commit: $(date)" || echo "Nothing to commit"

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull --rebase
          git push origin HEAD:main

